name: CMake auto checkout
on:
  push:
    branches:
      - master

jobs:
  updateBranches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: cmake
      - name: Checkout the changes to code files
        run: |
          git fetch
          git config user.name "CMake Update Bot" user.email "bot@www.spigot.com"
          git checkout origin/master ./GavinBackendDatasetUtils/*.cpp ./GavinBackendDatasetUtils/*.hpp README.md .gitignore .gitattributes
      - name: Commit new changes
        run: |
          git commit ./GavinBackendDatasetUtils/*.cpp ./GavinBackendDatasetUtils/*.hpp README.md .gitignore .gitattributes -m "Update files from master"
      - name: Push changes to CMake
        run: |
          git push
